"use client";
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {apiRequest} from '@/lib/api';
import {getSupabase} from '@/lib/supabase';
type Agent={user_id:string;name:string;email:string;active:boolean};
export default function Admin(){
 const router=useRouter();const [ready,setReady]=useState(false);const [agents,setAgents]=useState<Agent[]>([]);
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [company,setCompany]=useState('');const [password,setPassword]=useState('');
 const [version,setVersion]=useState('');const [secret,setSecret]=useState('');const [verify,setVerify]=useState('');const [configured,setConfigured]=useState<string[]>([]);
 const load=useCallback(async()=>{const result=await apiRequest<{agents:Agent[]}>('/api/admin/agents');setAgents(result.agents);const settings=await apiRequest<{configured:string[]}>('/api/admin/settings');setConfigured(settings.configured);},[]);
 useEffect(()=>{void(async()=>{try{const {profile}=await apiRequest<{profile:{role:string}}>('/api/account');if(profile.role!=='SUPER_ADMIN'){router.replace('/agen');return;}setReady(true);await load();}catch{router.replace('/admin/login');}})();},[load,router]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{await apiRequest('/api/admin/agents',{action:'create',name,email,company,password});setPassword('');setName('');setEmail('');setCompany('');setNotice('Akun agen dan workspace berhasil dibuat. Berikan email dan kata sandi kepada agen melalui jalur pribadi.');await load();}catch(e){setError(e instanceof Error?e.message:'Gagal membuat akun');}finally{setBusy(false);}}
 async function toggle(a:Agent){setBusy(true);setError('');try{await apiRequest('/api/admin/agents',{action:'toggle',userId:a.user_id,active:!a.active});await load();}catch(e){setError(e instanceof Error?e.message:'Gagal mengubah akses');}finally{setBusy(false);}}
 async function settings(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await apiRequest('/api/admin/settings',{version,appSecret:secret,verifyToken:verify});setSecret('');setVerify('');setNotice('Pengaturan Meta tersimpan. Pasang callback webhook di aplikasi Meta, lalu hubungkan WABA melalui portal agen.');await load();}catch(e){setError(e instanceof Error?e.message:'Pengaturan gagal');}finally{setBusy(false);}}
 if(!ready)return <main className="app-main">Memeriksa akses super admin…</main>;
 return <main className="app-main admin-portal"><header className="app-title"><div><span className="eyebrow">IMBABC · SUPER ADMIN</span><h1>Kelola akun agen</h1><p>Akses, workspace, dan pengaturan aplikasi WhatsApp.</p></div><div><Button variant="outline" asChild><Link href="/agen/login">Portal agen</Link></Button> <Button variant="outline" onClick={async()=>{await getSupabase()?.auth.signOut();router.replace('/admin/login');}}>Keluar</Button></div></header>
 {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="form-notice" role="status">{notice}</p>}
 <div className="content-columns"><section className="content-panel"><h2>Agen ({agents.length})</h2><p>Menonaktifkan agen memblokir akses dan menghentikan pesan yang masih mengantre.</p>{agents.length?<Table><TableHeader><TableRow><TableHead>Nama / email</TableHead><TableHead>Status</TableHead><TableHead>Akses</TableHead></TableRow></TableHeader><TableBody>{agents.map(a=><TableRow key={a.user_id}><TableCell>{a.name}<br/>{a.email}</TableCell><TableCell>{a.active?'Aktif':'Nonaktif'}</TableCell><TableCell><Button variant="outline" disabled={busy} onClick={()=>toggle(a)}>{a.active?'Nonaktifkan':'Aktifkan'}</Button></TableCell></TableRow>)}</TableBody></Table>:<p>Belum ada agen. Buat akun pertama di formulir ini.</p>}</section>
 <section className="content-panel"><h2>Buat akun agen</h2><form className="form-stack" onSubmit={create}><label htmlFor="agent-name">Nama agen</label><Input id="agent-name" required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="agent-email">Email login</label><Input id="agent-email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="agent-company">Nama workspace</label><Input id="agent-company" required minLength={2} maxLength={100} value={company} onChange={e=>setCompany(e.target.value)}/><label htmlFor="agent-pass">Kata sandi awal (minimal 12 karakter)</label><Input id="agent-pass" type="password" autoComplete="new-password" required minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/><Button type="submit" disabled={busy} className="gradient-button">Buat akun dan workspace</Button></form></section></div>
 <section className="content-panel"><h2>Integrasi aplikasi Meta</h2><p>{configured.length===3?'Pengaturan tersimpan. Koneksi nomor dan template dilakukan oleh masing-masing agen.':'Isi pengaturan aplikasi Meta sebelum uji WhatsApp.'}</p><p>Callback webhook: <code className="break-all">{process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/imbabc-api/webhooks/meta/whatsapp</code></p><form className="form-stack" onSubmit={settings}><label htmlFor="meta-version">Versi Graph API aplikasi Meta (contoh format vXX.0)</label><Input id="meta-version" placeholder="Versi dari dashboard Meta" required pattern="v[0-9]{2}\.[0-9]+" value={version} onChange={e=>setVersion(e.target.value)}/><label htmlFor="meta-secret">App secret</label><Input id="meta-secret" type="password" required autoComplete="off" minLength={16} value={secret} onChange={e=>setSecret(e.target.value)}/><label htmlFor="meta-verify">Token verifikasi webhook (buat minimal 20 karakter)</label><Input id="meta-verify" type="password" required autoComplete="off" minLength={20} value={verify} onChange={e=>setVerify(e.target.value)}/><Button disabled={busy} type="submit">Simpan pengaturan Meta</Button></form></section>
 </main>;
}
